# Generated by Django 5.2.6 on 2025-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="download_token",
            field=models.CharField(
                db_index=True, default="", max_length=64, unique=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
